name: 'Tag Metadata'
description: 'Generate additional metadata for git tags'
outputs:
  count: 
    description: "The number of tags"
    value: ${{ steps.count.outputs.count }}
  height:
    description: "The number of commits since the last tag"
    value: ${{ steps.height.outputs.height }}
runs:
  using: "composite"
  steps:
    - name: Generate Count
      id: count
      shell: bash -l {0}
      run: |
        echo "::set-output name=count::$(
          git tag | 
          wc -l   
        )"
    - name: Generate Height
      id: height
      shell: bash
      env:
          COUNT: ${{ steps.count.outputs.count }}
      run: |
        if (( $COUNT > 0 )); then
          echo "::set-output name=height::$(git rev-list $(git describe --abbrev=0 --tags).. --count)"
        else
          echo "::set-output name=height::$(git rev-list --count)"
        fi