name: 'Tag Metadata'
description: 'Generate additional metadata for git tags'
branding:
  icon: 'git-commit'
  color: 'blue'
outputs:
  count: 
    description: "The number of tags"
    value: ${{ steps.count.outputs.count }}
  height:
    description: "The number of commits since the latest tag"
    value: ${{ steps.height.outputs.height }}    
  tag:
    description: "The latest tag"
    value: ${{ steps.version.outputs.tag }}
  version:
    description: "The semantic version of the latest tag"
    value: ${{ steps.version.outputs.version }}
  major:
    description: "The major version of the latest tag"
    value: ${{ steps.version.outputs.major }}
  minor:
    description: "The minor version of the latest tag"
    value: ${{ steps.version.outputs.minor }}
  patch:
    description: "The patch version of the latest tag"
    value: ${{ steps.version.outputs.patch }}
runs:
  using: "composite"
  steps:
    - name: Generate Count
      id: count
      shell: bash -l {0}
      run: |
        echo "count=$(
          git tag | 
          wc -l   
        )" >> $GITHUB_OUTPUT
    - name: Version
      id: version
      shell: bash
      run: |
        tag=${GITHUB_REF/refs\/tags\//}
        version=${tag#v}
        major=${version%%.*}
        minor=${version%.*}
        minor=${minor#*.}
        patch=${version##*.}
        echo "tag=${tag}" >> $GITHUB_OUTPUT
        echo "version=${version}" >> $GITHUB_OUTPUT
        echo "major=${major}" >> $GITHUB_OUTPUT
        echo "minor=${major}" >> $GITHUB_OUTPUT
        echo "patch=${major}" >> $GITHUB_OUTPUT
    - name: Generate Height
      id: height
      shell: bash
      env:
          COUNT: ${{ steps.count.outputs.count }}
          TAG: ${{ steps.tag.outputs.tag }}
      run: |
        if (( $COUNT > 0 )); then
          echo "height=$(git rev-list $TAG.. --count)" >> $GITHUB_OUTPUT
        else
          echo "height=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT
        fi