name: Test

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test-shallow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test Shallow 
        id: test
        uses: ./

      - name: Test
        run: |
          if (( ${{ steps.test.outputs.height }} != 0 )); then
            exit 1
          fi
          if (( ${{ steps.test.outputs.count }} != 0 )); then
            exit 1
          fi
